<img src="https://upload.wikimedia.org/wikipedia/commons/3/35/Uba_fiuba_ingenieria_logo.png" width="300" align="center">



# **Analisis de Series de Tiempo II**

# **Clase 5, Convoluciones 1D**

Importamos lo necesario

In [ ]:
import numpy as np
import tensorflow as tf

Definimos señal de entrada

In [ ]:
x = np.array([[1, 2, 3, 4, 5]], dtype=np.float32)
print(x)

[[1. 2. 3. 4. 5.]]


Convertimos a entrada que recibe TF

In [ ]:
# (batch, longitud, canales)
x = x.reshape(1, 5, 1)

## **A) Conv1D Normal**

Definimos convolución normal

In [ ]:
conv = tf.keras.layers.Conv1D(
    filters=1,
    kernel_size=3,
    padding="same",
    use_bias=False
)

Construimos la capa

In [ ]:
conv.build((1,5,1))

Definimos manualmente el kernel

In [ ]:
kernel = np.array([[[1]],
                   [[1]],
                   [[1]]], dtype=np.float32)

conv.set_weights([kernel])

Resultado

In [ ]:
y = conv(x)

In [ ]:
print("Entrada:")
print(x[0,:,0])

print("\nSalida:")
print(y.numpy()[0,:,0])

Entrada:
[1. 2. 3. 4. 5.]

Salida:
[ 3.  6.  9. 12.  9.]


## **B) Conv1D Causal**

Definimos convolución causal

In [ ]:
conv = tf.keras.layers.Conv1D(
    filters=1,
    kernel_size=3,
    padding="causal",
    use_bias=False
)

In [ ]:
conv.build((1,5,1))

kernel = np.array([[[1]],
                   [[1]],
                   [[1]]], dtype=np.float32)

conv.set_weights([kernel])

Resultado

In [ ]:
y = conv(x)

print("Entrada")
print(x[0,:,0])

print("\nSalida")
print(y.numpy()[0,:,0])

Entrada
[1. 2. 3. 4. 5.]

Salida
[ 1.  3.  6.  9. 12.]


## **C) Conv1D Dilatada**

In [ ]:
conv = tf.keras.layers.Conv1D(
    filters=1,
    kernel_size=3,
    dilation_rate=2,
    padding="same",
    use_bias=False
)

In [ ]:
conv.build((1,8,1))

kernel = np.array([[[1]],
                   [[1]],
                   [[1]]], dtype=np.float32)

conv.set_weights([kernel])

Resultado

In [ ]:
y = conv(x)

print("Entrada")
print(x[0,:,0])

print("\nSalida")
print(y.numpy()[0,:,0])

Entrada
[1. 2. 3. 4. 5.]

Salida
[4. 6. 9. 6. 8.]
